### ISSUE TITLE
Cherry oak breaking?

### ISSUE THREAD

**Issue by Catahoula7896** [DawnTeamMC/Promenade#108]
### What happened?

So i added a few more mods to the world (just some bosses and mini bosses) and now cherry oak seems to be messed up, it says it is the correct item in your inventory then when you place it the block reverts to a different cherry oak block (leaves turn into fences that kinda stuff)

### Dawn API version

dawn-3.5.0.jar

### Fabric API version

0.14.12

**Comment by Hugman76** [comment]
You are not using the latest version of Dawn API. Only the latest versions of my mods are supported.
