### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Rogenar** [DawnTeamMC/Promenade#118]
### What happened?

My game crashes on Promenade version 3.1.0. Version 3.0.1 is working.
[crash-2023-03-26_14.37.30-client.txt](https://github.com/DawnTeamMC/Promenade/files/11071445/crash-2023-03-26_14.37.30-client.txt)
[latest.log](https://github.com/DawnTeamMC/Promenade/files/11071446/latest.log)
[rei.log](https://github.com/DawnTeamMC/Promenade/files/11071447/rei.log)
[rei-issues.log](https://github.com/DawnTeamMC/Promenade/files/11071448/rei-issues.log)

### Dawn API version

3.1.0

### Fabric API version

0.14.18-1.19.3

### Relevant log output

```shell
[crash-2023-03-26_14.37.30-client.txt](https://github.com/DawnTeamMC/Promenade/files/11071445/crash-2023-03-26_14.37.30-client.txt)
[latest.log](https://github.com/DawnTeamMC/Promenade/files/11071446/latest.log)
```

**Comment by Hugman76** [comment]
You need to update the Blockus mod: https://www.curseforge.com/minecraft/mc-mods/blockus/files/4408005 :D

**Comment by Rogenar** [comment]
blockus version 2.6.1 works, but in version 2.6.2 the game crashes without opening. 
[latest.log](https://github.com/DawnTeamMC/Promenade/files/11071864/latest.log)
[rei.log](https://github.com/DawnTeamMC/Promenade/files/11071865/rei.log)
[rei-issues.log](https://github.com/DawnTeamMC/Promenade/files/11071866/rei-issues.log)
[crash-2023-03-26_17.25.07-client.txt](https://github.com/DawnTeamMC/Promenade/files/11071867/crash-2023-03-26_17.25.07-client.txt)

**Comment by Hugman76** [comment]
Blockus v2.6.2 is compatible with Promenade v3.1.0. (latest)
Blockus v2.6.1 is compatible with Promenade v3.0.1. (previous to latest)

Your crash reports demonstrate you've tried to launch the game with Blockus v2.6.1 + Promenade v3.0.1, and then with Blockus v2.6.2 + Promenade v3.1.0...

**Comment by Rogenar** [comment]
I have tested that it is compatible with blockus 2.6.3 mod promenade 3.1.0 and it is compatible. Problem solved. Thanks.
