### ISSUE TITLE
Incompatible Version of Fabric API on 1.20.0

### ISSUE THREAD

**Issue by RhapsPerhaps** [DawnTeamMC/Promenade#149]
### What happened?

Hello! I've been testing various 1.20 mods and I really wanted to give Promenade a try, but I keep getting the following error. I believe I have the latest version of everything you can have with 1.20.0, and I also tried it with just Promenade, Dawn, and Fabric API and received the exact same error as I had been when using other mods as well. 

However when I swapped everything to 1.20.1 it allowed me to download the 0.83.1 version of Fabric API so I believe the actual issue is that the version of Fabric API this uses is not available for 1.20.0 but this mod is listed as being available for 1.20.0. (I double checked Fabric API's page and only see the 0.83.1 version listed for 1.20.1 as well.) 

I realize I kind of solved my own issue as I was writing this but I still wanted to drop it along in case it's a versioning issue you wanted to fix. Thanks!

### Dawn API version

5.0

### Fabric API version

0.83.0+1.20

### Relevant log output

```shell
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Promenade' (promenade) 4.1.0 with any version that is compatible with:
		 - fabric-api 0.83.0+1.20
Unmet dependency listing:
	 - Mod 'Promenade' (promenade) 4.1.0 requires version 0.83.1 or later of mod 'Fabric API' (fabric-api), but only the wrong version is present: 0.83.0+1.20!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

**Comment by Hugman76** [comment]
Promenade requires Fabric API 0.83.1 because of a fix I specifically reported. This version came out as soon as 1.20.1 releases hence why Fabric API now tags all versions above this one to support 1.20.1. However, it still supports 1.20. In fact, most of mods (if not all of them), built on 1.20 or 1.20.1 do support 1.20 AND 1.20.1. Feel free to choose whatever version you want to play, even though 1.20.1 contains some crash fixes.
