### ISSUE TITLE
Promenade removes the ability for pickaxes to be used

### ISSUE THREAD

**Issue by TrueDevron** [DawnTeamMC/Promenade#150]
### What happened?

I've tried removing countless mods beforehand and found that Promenade does something that makes any pickaxe unable to mine/collect anything. It acts as if it is being mined with the players fist.

I've also tried with Dawn API and no Promenade but that fixes the issue, I also can't find any log output either, though I may not be looking in the right file.

Note: I am using Quilt, which may a cause of the bug, haven't tested with Fabric itself

### Dawn API version

5.0.0

### Fabric API version

0.83.1

**Comment by Hugman76** [comment]
If you can try with Fabric that'd be great! Also if you have logs please send them. I've never encountered something like that and I have honestly no idea where this could be coming from.

**Comment by TrueDevron** [comment]
Nevermind -- it was an issue with Promenade + Excavated Variants failing to register as wasn't updated to the Asphalt rename. It's been fixed with EV 3.0.3, sorry about that.
