### ISSUE TITLE
Standard file naming convention

### ISSUE THREAD

**Issue by xanthian** [DawnTeamMC/Promenade#152]
### What is your idea about?

Sorry but please stick to standard naming convention of blocks and associated json files.
Making any compatibility for Promenade is an absolute nightmare due to how you have named the files, especially when using datagen.

eg..

maple/planks.

should be maple_planks

**Comment by Hugman76** [comment]
The conventional naming is inconvenient to me because I do not do datagen and it rapidly becomes a burden to find files through this. Sorry.
