### ISSUE TITLE
Placing Slabs Crash Me Outta Server

### ISSUE THREAD

**Issue by ZomboDemonNeko** [DawnTeamMC/Promenade#160]
### What happened?

So a friend of mine set up a server where this mod is used (Its the Better MC Fabric BMC2 modpack) and for some reason every time i place ANY slab it crashes me out of the server and i have no idea why 

### Dawn API version

idk

**Comment by Hugman76** [comment]
Could not reproduce, this bug is not the latest version of Promenade, especially with Dawn API version "idk"
