### ISSUE TITLE
Sakura Groves try to use the nonexistent music provider promenade:music.overworld.sakura_groves

### ISSUE THREAD

**Issue by lumiscosity** [DawnTeamMC/Promenade#164]
### What happened?

Both of the Sakura Grove biomes try to use the `promenade:music.overworld.sakura_groves` music provider, which doesn't exist.

### Dawn API version

5.0.0

**Comment by Hugman76** [comment]
Do you have a log for this? I can't reproduce it

**Comment by lumiscosity** [comment]
this doesn't produce any logs unless you're using a mod such as (Cyanide)[https://github.com/alcatrazEscapee/cyanide], in which case, the following log is produced when trying to make a world: https://mclo.gs/wTYcPGA
