### ISSUE TITLE
Add boats and signs for the different wood types

### ISSUE THREAD

**Issue by kotx** [DawnTeamMC/Promenade#18]

**Comment by Dhranios** [comment]
Also affects dark amaranth and palm.
Recipe files, recipe unlock advancement files, textures, etc. it's all missing.
They're simply not implemented.

**Comment by Hugman76** [comment]
Closed in favor of DawnTeamMC/DawnAPI#11

**Comment by Hugman76** [comment]
Reopened because it did not make sense to close it in the first place
