### ISSUE TITLE
Leaf Particles in Weird Places

### ISSUE THREAD

**Issue by mertatilgan** [DawnTeamMC/Promenade#180]
### What happened?

The entire promenade:cernelian_treeway biome has leaf particles. Whether I'm in the sky or underground, leaves are everywhere in this biome.

The way leaf particles are spawned should be similar to Cherry blossom trees from.
![image](https://github.com/DawnTeamMC/Promenade/assets/35312870/c8a5bb29-c910-48a8-88e5-c1ed6554a8d0)

### Dawn API version

5.0.0

### Fabric API version

0.91.0+1.20.1

**Comment by Hugman76** [comment]
Biome particles will be moved to the leaf blocks - kinda like the cherry trees - in the next version. This issue can therefore be closed prematurely
