### ISSUE TITLE
Broken World Generation

### ISSUE THREAD

**Issue by UnusedCactus** [DawnTeamMC/Promenade#23]
![2021-10-10_08 10 50](https://user-images.githubusercontent.com/87100678/136695392-d03baa9e-2035-45d2-9c52-6af8491f18c9.png)
![2021-10-10_08 08 06](https://user-images.githubusercontent.com/87100678/136695416-372e575e-3af0-401a-9a44-e50528d4ea1d.png)

Promenade breaks world generation along chunk borders (as seen in the screenshots). I have no problems with this, however others might.

**Comment by Hugman76** [comment]
Cannot reproduce this! Sorry.
