### ISSUE TITLE
Not loading properly?

### ISSUE THREAD

**Issue by Plutonium-239** [DawnTeamMC/Promenade#29]
![image](https://user-images.githubusercontent.com/29684689/139596336-a7b673ac-9d18-4793-8dbc-059dbd6267a1.png)

I am running this on a server. This is supposed to be a pink cherry oak forest. Am I supposed to download a resource pack to go with this? This acts completely broken, there are invisible blocks I can't interact with, water/lava doesn't show where it is supposed to be someplace (but it actually is there)
I'm using latest fabric loader, fabric API, dawn API and promenade.

**Comment by Hugman76** [comment]
You are supposed to have the same versions of the mod and the Dawn API on the client and on the server. The biome placement looks completely unatural, which makes me think you have installed the mod on the client but not the server.
