### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors, provided by 'promenade'!

### ISSUE THREAD

**Issue by Jkj61Abn** [DawnTeamMC/Promenade#51]
Hi, anyone can help us understand what is issue cause, any idea how to fix?

https://paste.ee/p/6YbTc

---- Minecraft Crash Report ----

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'promenade'!
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
    at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
    at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
    at net.minecraft.class_310.<init>(class_310.java:452)
    at net.minecraft.client.main.Main.main(Main.java:199)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: com/hugman/dawn/api/creator/bundle/block/MTBlockBundle
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:467)
    at com.google.common.reflect.Reflection.initialize(Reflection.java:66)
    at com.hugman.promenade.Promenade.initBundle(Promenade.java:29)
    at com.hugman.promenade.Promenade.initBundles(Promenade.java:38)
    at com.hugman.promenade.Promenade.onInitialize(Promenade.java:23)
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
    ... 11 more
Caused by: java.lang.ClassNotFoundException: com.hugman.dawn.api.creator.bundle.block.MTBlockBundle
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    ... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
    at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
    at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
    at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
    Modules: 
        ADVAPI32.dll:Расширенная библиотека API Windows 32:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        COMCTL32.dll:Библиотека элементов управления взаимодействия с пользователем:6.10 (WinBuild.160101.0800):Microsoft Corporation
        CRYPT32.dll:API32 криптографии:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
        CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
        DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation
        DNSAPI.dll:Динамическая библиотека API DNS-клиента:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        GDI32.dll:GDI Client DLL:10.0.19041.1202 (WinBuild.160101.0800):Microsoft Corporation
        IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
        IPHLPAPI.DLL:API вспомогательного приложения IP:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        KERNEL32.DLL:Библиотека клиента Windows NT BASE API:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        KERNELBASE.dll:Библиотека клиента Windows NT BASE API:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        NLAapi.dll:Network Location Awareness 2:10.0.19041.1151 (WinBuild.160101.0800):Microsoft Corporation
        NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation
        NTASN1.dll:Microsoft ASN.1 API:10.0.19041.320 (WinBuild.160101.0800):Microsoft Corporation
        Ole32.dll:Microsoft OLE для Windows:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation
        POWRPROF.dll:DLL модуля поддержки профиля управления питанием:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
        Pdh.dll:Модуль поддержки данных производительности Windows:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        RPCRT4.dll:Библиотека удаленного вызова процедур:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        SHCORE.dll:SHCORE:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        SHELL32.dll:Общая библиотека оболочки Windows:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        UMPDC.dll
        USER32.dll:Многопользовательская библиотека клиента USER API Windows:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        USERENV.dll:Userenv:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
        VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
        WINHTTP.dll:Службы HTTP Windows:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        WINMM.dll:MCI API DLL:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        WS2_32.dll:32-разрядная библиотека Windows Socket 2.0:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation
        WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        Wldp.dll:Политика блокировки Windows:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        amsi.dll:Anti-Malware Scan Interface:10.0.19041.746 (WinBuild.160101.0800):Microsoft Corporation
        aswAMSI.dll:Avast AMSI COM object:21.11.6809.0:AVAST Software
        aswhook.dll:Avast Hook Library:21.11.6809.0:AVAST Software
        bcrypt.dll:Библиотека криптографических примитивов Windows:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
        combase.dll:Microsoft COM для Windows:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
        dhcpcsvc.DLL:Служба DHCP-клиента:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        dhcpcsvc6.DLL:Клиент DHCPv6:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        fwpuclnt.dll:API пользовательского режима FWP/IPsec:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        gdi32full.dll:GDI Client DLL:10.0.19041.1387 (WinBuild.160101.0800):Microsoft Corporation
        glfw.dll
        java.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
        javaw.exe:OpenJDK Platform binary:17.0.1.0:Microsoft
        jemalloc.dll
        jimage.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
        jli.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
        jna12837204404948526822.dll:JNA native library:6.1.1:Java(TM) Native Access (JNA)
        jvm.dll:OpenJDK 64-Bit server VM:17.0.1.0:Microsoft
        kernel.appcore.dll:AppModel API Host:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
        lwjgl.dll
        management.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
        management_ext.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
        msvcp140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
        msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
        msvcrt.dll:Windows NT CRT DLL:7.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
        mswsock.dll:Расширение поставщика службы API Microsoft Windows Sockets 2.0:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        napinsp.dll:Поставщик оболочки совместимости для имен электронной почты:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        ncrypt.dll:Маршрутизатор Windows NCrypt:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        net.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
        nio.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
        ntdll.dll:Системная библиотека NT:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        perfos.dll:Библиотека объектов производительности системы Windows:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        pnrpnsp.dll:Поставщик пространства имен PNRP:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        profapi.dll:User Profile Basic API:10.0.19041.844 (WinBuild.160101.0800):Microsoft Corporation
        rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
        rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.320 (WinBuild.160101.0800):Microsoft Corporation
        sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.320 (WinBuild.160101.0800):Microsoft Corporation
        shlwapi.dll:Библиотека небольших программ оболочки:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        sunmscapi.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
        svml.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
        ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
        vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
        verify.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
        win32u.dll:Win32u:10.0.19041.1387 (WinBuild.160101.0800):Microsoft Corporation
        windows.storage.dll:API хранения Microsoft WinRT:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
        winrnr.dll:LDAP RnR Provider DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
        wshbth.dll:Windows Sockets Helper DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
        zip.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
Stacktrace:
    at net.minecraft.client.main.Main.main(Main.java:199)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
    Minecraft Version: 1.18.1
    Minecraft Version ID: 1.18.1
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 17.0.1, Microsoft
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
    Memory: 764057328 bytes (728 MiB) / 2113929216 bytes (2016 MiB) up to 2147483648 bytes (2048 MiB)
    CPUs: 4
    Processor Vendor: GenuineIntel
    Processor Name: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Identifier: Intel64 Family 6 Model 142 Stepping 9
    Microarchitecture: Amber Lake
    Frequency (GHz): 2,71
    Number of physical packages: 1
    Number of physical CPUs: 2
    Number of logical CPUs: 4
    Graphics card #0 name: Intel(R) HD Graphics 620
    Graphics card #0 vendor: Intel Corporation (0x8086)
    Graphics card #0 VRAM (MB): 1024,00
    Graphics card #0 deviceId: 0x5916
    Graphics card #0 versionInfo: DriverVersion=24.20.100.6286
    Memory slot #0 capacity (MB): 4096,00
    Memory slot #0 clockSpeed (GHz): 2,13
    Memory slot #0 type: DDR4
    Memory slot #1 capacity (MB): 4096,00
    Memory slot #1 clockSpeed (GHz): 2,13
    Memory slot #1 type: DDR4
    Virtual memory max (MB): 14016,16
    Virtual memory used (MB): 9124,15
    Swap memory total (MB): 6398,73
    Swap memory used (MB): 604,55
    JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
    Fabric Mods: 
        adorn: Adorn 3.0.0+1.18.1
        architects_palette: Architect's Palette Fabric 1.3
        architectury: Architectury 3.2.56
        blue_endless_jankson: jankson 1.2.1
        cardinal-components-base: Cardinal Components API (base) 4.0.0
        cardinal-components-entity: Cardinal Components API (entities) 4.0.0
        cloth-basic-math: cloth-basic-math 0.6.0
        cloth-config: Cloth Config v6 6.1.48
        com_eliotlash_mclib_mclib: mclib 18
        com_eliotlash_molang_molang: molang 18
        comforts: Comforts 1.0.0-1.18
        dawn: Dawn API 3.2.0
        fabric: Fabric API 0.44.0+1.18
        fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
        fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
        fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
        fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
        fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
        fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
        fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
        fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
        fabric-copper-golem: Copper Golem 1.0.3+1.18
        fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
        fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
        fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
        fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
        fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
        fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
        fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
        fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
        fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
        fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
        fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
        fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
        fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
        fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
        fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
        fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
        fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
        fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
        fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
        fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
        fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
        fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
        fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
        fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
        fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
        fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
        fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
        fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
        fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
        fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8
        fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
        fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
        fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
        fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
        fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
        fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
        fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
        fabricloader: Fabric Loader 0.12.12
        fallingtree: FallingTree 2.16.1
        geckolib3: Geckolib 3.0.22
        gobber2: Gobber2 2.5.54
        imm_ptl_core: Immersive Portals Core 1.1.4
        immersive_portals: Immersive Portals 1.1.4
        jankson: Jankson 4.0.0+j1.2.0
        java: OpenJDK 64-Bit Server VM 17
        libcd: LibCapableData 3.0.3+1.16.3
        libgui: LibGui 5.1.0+1.18
        libninepatch: LibNinePatch 1.1.0
        minecraft: Minecraft 1.18.1
        org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
        org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
        org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
        org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
        org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
        org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
        org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
        org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
        org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
        promenade: Promenade 2.2.0
        pugh_lib: Pugh Lib 1.2.12
        pugh_tools: Pugh Tools 1.1.14
        q_misc_util: QMiscUtil 1.1.4
        ratsmischief: Rat's Mischief 1.3.3
        roughlyenoughitems: Roughly Enough Items 7.1.356
        simple_shelves: Simple Shelves 1.0.4
        soaringstructures2: Soaring Structures 2 1.18 - 2.0
        terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
        valley: ValleyCraft 2.1
        xaerominimap: Xaero's Minimap 21.22.5
    Launched Version: fabric-loader-0.12.12-1.18.1
    Backend library: LWJGL version 3.2.2 build 10
    Backend API: Unknown
    Window size: <not initialized>
    GL Caps: Using framebuffer using OpenGL 3.2
    GL debug messages: <disabled>
    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'fabric'
    Type: Client (map_client.txt)
    CPU: <unknown>

**Comment by Hugman76** [comment]
You need to update Promenade to the [latest version (v2.2.1).](https://www.curseforge.com/minecraft/mc-mods/artisanat/files/3575056)

**Comment by Jkj61Abn** [comment]
thx
