### ISSUE TITLE
Improve cherry oak forests

### ISSUE THREAD

**Issue by Hugman76** [DawnTeamMC/Promenade#57]
- [x] Add cute little rocks
- [x] Add cute little puddles
- [x] Add cute little bamboo
- [x] #78
- [x] Add cute little foxes
- [x] Add cute little pandas
- [x] Add cute little flying petals as particles
- [x] Add coarse dirt bands
- [x] Change color of grass (more blue)

Inspiration screenshots from Genshin Impact:
![image](https://user-images.githubusercontent.com/36963654/149639895-9fcc0ea2-e3ea-4261-a40a-5b49be41b992.png)
![image](https://user-images.githubusercontent.com/36963654/149639898-a6d12c9f-82cd-4d5d-a305-67995763713d.png)

**Comment by Dhranios** [comment]
Too much cuteness, needs more inspiring things.
I suggest replacing cute rocks with thoughtful rocks, and epic large lavender flower patches!

😁
