### ISSUE TITLE
Nether biomes don't generate when TerraBlender is installed

### ISSUE THREAD

**Issue by SargRReal** [DawnTeamMC/Promenade#62]
Yeah basically the title. I try to /locatebiome the biomes and it will always say it can't find any in a reasonable distance.

**Comment by Hugman76** [comment]
Please provide more detail.
Are you talking about overworld biomes? What versions of the mods are you using?

**Comment by MarkNoName** [comment]
Agreed. Nether and End Biomes are not generating. Using TerraBlender with default configs

**Comment by SargRReal** [comment]
> 

I'm using the latest version promenade 2.5.0 on 1.18.1 with TerraBlender Fabric 1.18.1-1.1.0.73

biomes in both the nether and end do not spawn at all

**Comment by Hugman76** [comment]
End biomes are known to be disabled at the moment, but nether biomes are available only if TerraBlender is not installed. We're looking into it.

**Comment by Hugman76** [comment]
Created #63 for the end biome issue.

**Comment by MarkNoName** [comment]
Can i ask you, why the end biomes are disabled?

**Comment by Hugman76** [comment]
At the moment, we have a bug where no world feature (hyphae, roots, obsidian spikes) can generate in the end biomes.
