### ISSUE TITLE
Dark amaranth features do not generate

### ISSUE THREAD

**Issue by Hugman76** [DawnTeamMC/Promenade#63]
This is why the biomes are currently disabled. I have no idea why this occurs. I'll take a look at the placement algorithms themselves.

**Comment by Roadhog360** [comment]
If the fix was datapack features, could this reasonably and easily be backported to 1.18.2? I just noticed this and my heart sank because the amaranth biome is one of the biggest reasons I downloaded the mod. Please backport the fix...
