### ISSUE TITLE
Crash while starting server

### ISSUE THREAD

**Issue by TheButterbrotMan** [DawnTeamMC/Promenade#70]
https://bytebin.lucko.me/Dy2wppDp80

**Comment by Hugman76** [comment]
I do not think that's an issue with Promenade. Your game is missing a ton of assets and classes. I recommend that you re-install your whole game.

**Comment by TheButterbrotMan** [comment]
My game is working fine, when i remove your mod. So im pretty sure its connected to your mod? Could you please checkout if you can solve it.

**Comment by Hugman76** [comment]
I have looked at it before my previous comment, and read through it again. I still cannot find any issue related to my mod. You still have a ton of mods with malformed JSON files, missing models, missing sounds, missing textures.

**Comment by Hugman76** [comment]
Your log is honestly terrifying dude.

**Comment by TheButterbrotMan** [comment]
No problem, im open to help, what information do you need?

**Comment by TheButterbrotMan** [comment]
Also this happend on clientside. So could be the built-in server.

**Comment by TheRanker** [comment]
this also crashes on client side when you create a new world.  he provided enough information in the crash for your issue. please be respectful and look at your own code.

**Comment by Hugman76** [comment]
> this also crashes on client side when you create a new world. he provided enough information in the crash for your issue. please be respectful and look at your own code.

I have been respectful through the process. I have looked at my own code already, but 90% of time bugs can be directly pointed from the crash log. That was not the case here, and I know what I am saying.
As for information, I needed to know what version the code was running on, and what side it was running on, as crashes can come from both client and server.

**Comment by Hugman76** [comment]
As for the issue itself, I think I have indentified it. This comes from one of the latest commits, probably with the way I register the witch huts. Will be looking at it in free time, as I am doing this while in class.

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed for the next version.
But as I said, you also have 500+ mods downloaded. Some of them contain a LOT of dangerous data mistakes and loading.

**Comment by TheButterbrotMan** [comment]
When this fix will be available on curseforge?

**Comment by Hugman76** [comment]
Later today
