### ISSUE TITLE
Nether biome generation is turned off by default

### ISSUE THREAD

**Issue by FwuffyPetsOwO** [DawnTeamMC/Promenade#77]
### What happened?

The `/locatebiome` command fails to find any of the five Promenade Nether Biomes in 1.18.2, regardless of the existence (or lack thereof) of other mods like TerraBlender. I am using Promenade version `2.6.1`. There are no errors in the log files. I have tested with Fabric Loader versions `0.13.3` and `0.14.3` and this issue is present with both.

### Dawn API version

3.3.0

### Fabric API version

0.51.1+1.18.2

**Comment by Hugman76** [comment]
Can reproduce. This is very weird, since I add them both via vanilla and as a TerraBlender region...

**Comment by Hugman76** [comment]
I reported bug on TerraBlender's repository, assuming it comes from the API itself: https://github.com/Glitchfiend/TerraBlender/issues/66

**Comment by Hugman76** [comment]
Okay, it is infuriating how DUMB I am.
I set the default option for nether biome spawning to FALSE!

https://github.com/DawnTeamMC/Promenade/blob/b4e616e1a7ccea48fc7dd1473c0e758233ea64fe/src/main/java/com/hugman/promenade/config/PromenadeConfig.java#L34

https://github.com/DawnTeamMC/Promenade/blob/b4e616e1a7ccea48fc7dd1473c0e758233ea64fe/src/main/java/com/hugman/promenade/config/PromenadeConfig.java#L36

If you wish to turn them on again, you can do so turning the setting on again (via ModMenu in the Mods screen, or in the `.minecraft\config\promenade\biomes.json` file, replace `false` with `true`)
I deeply apologise for this mistake, to you and everyone that would see this ticket. I am so, so stupid.

**Comment by FwuffyPetsOwO** [comment]
Oop, glad to dee that this was a simple issue. Everyone makes silly mistakes sometimes, an in the end there's no harm done here. Good luck with the future of this mod, you've done really great work so far and I'm quite excited to see what else you can do :)
