### ISSUE TITLE
Game crashes when trying to create a new world

### ISSUE THREAD

**Issue by TheButterbrotMan** [DawnTeamMC/Promenade#84]
### What happened?

I tried to create a new world, then happend this.

### Dawn API version

3.3.0

### Fabric API version

0.53.4+1.18.2

### Relevant log output

```shell
https://bytebin.lucko.me/SVmrvc6iGj
```

**Comment by Hugman76** [comment]
Looks like I did a huge mistake. I won't be able to provide a patch for the next 5 hours or so.

**Comment by Hugman76** [comment]
I cannot reproduce the issue by playing with Dawn API, Promenade and their required mods.

**Comment by Hugman76** [comment]
New details about the issue:
It seems like the game tries to load world generation stuff before the modded datapacks get loaded while creating a world.
The Fabric API is in charge of loading the mod datapacks, so I will create a ticket about this in their repository.

**Comment by Hugman76** [comment]
And here's the Fabric API ticket: https://github.com/FabricMC/fabric/issues/2259

**Comment by Hugman76** [comment]
I have rolled back the breaking changes of Promenade v2.6.2, and published Promenade v2.6.3, which fixes this issue.
