### ISSUE TITLE
Add a translation key for biomes

### ISSUE THREAD

**Issue by foul-fortune-feline** [DawnTeamMC/Promenade#86]
### What is your idea about?

Pretty much what is said on the tin. Minimap mods and such tend to have options to display biome names and it makes a mess when the translation key is displayed instead of... the translation haha

**Comment by Dhranios** [comment]
https://github.com/DawnTeamMC/Promenade/blob/f80419677096a0f6a485f343522db376154652ac/src/main/resources/assets/promenade/lang/en_us.json#L174

They already exist.

**Comment by foul-fortune-feline** [comment]
Ah yea I messed up and submitted this report to the wrong repo -w-'
