### ISSUE TITLE
Option to disable fruit drops?

### ISSUE THREAD

**Issue by sisby-folk** [DawnTeamMC/Promenade#92]
### What is your idea about?

As a modpack dev, I love the extra wood types but would love to turn off the fruit drops so that all food in my pack has more extensive cooking paths (through farmer's delight in my case)

**Comment by Hugman76** [comment]
You can change their loot tables

**Comment by sisby-folk** [comment]
Oh crow this is probably datapackable yes? what is it, drops from leaves?

**Comment by Hugman76** [comment]
Yes

**Comment by sisby-folk** [comment]
welp, you've got me there, that makes sense - I'll rip open the internal
datapack and figure it out. feel free to close this one.
