### ISSUE TITLE
Separate enable/disable configuration for upside-down mushroom galleries

### ISSUE THREAD

**Issue by neilkirklin** [DawnTeamMC/Promenade#93]
### What is your idea about?

The normal upright mushrooms covering the entirety of nether wastes can be exhausting to traverse, but the upside down ones on the ceiling don't obstruct view, don't impede ground movement, and introduce more verticality. A way to disable the ground mushrooms but keep ceiling mushrooms enabled would be very welcome.

**Comment by Hugman76** [comment]
The concerned feature(s) have been removed altogether, which makes this ticket obsolete.
