### ISSUE TITLE
Quilt incompatbility

### ISSUE THREAD

**Issue by Kuggle01** [DawnTeamMC/Promenade#95]
### What happened?

The mod will not work on Quilt 1.19.2, I've tried the mod on Quilt 1.18.2 and it does work.

### Dawn API version

3.5.0

### Fabric API version

Not using fabric, using QFapi version 4.0.0

### Relevant log output

```shell
https://paste.ee/p/RQDzW
```

**Comment by SylvKT** [comment]
Is Quilt compatibility not planned?

**Comment by Hugman76** [comment]
No but it should be compatible now
