### ISSUE TITLE
Compatibility with Nullscapes

### ISSUE THREAD

**Issue by Bluyidark** [DawnTeamMC/Promenade#96]
### What is your idea about?

Hi! I tried using Promenade and Nullscapes together for the End generation, apparently only nullscapes's biomes were generated whilst Promenade's Dark Amaranth Forest didn't, so I wanna ask if there will be compatibility with Nullscape in the future?

**Comment by Hugman76** [comment]
As Nullscapes is a datapack, it is currently overwriting the entire Ender generation, and will make it impossible for any mod to add any new biome to the Ender.
This could be solved by having Nullscapes as a mod that would add its biomes via the Fabric API!
